# Generated by Django 3.2.8 on 2021-10-15 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordersapp', '0002_auto_20211014_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'формируется'), ('STP', 'отправлен в обработку'), ('PD', 'оплачен'), ('PRD', 'обрабатывается'), ('RDY', 'исполнен'), ('CNC', 'отменен')], default='FM', max_length=3, verbose_name='Статус'),
        ),
    ]
