# Generated by Django 3.2.8 on 2021-10-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_auto_20211015_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
