# Generated by Django 3.2.8 on 2021-10-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0005_auto_20211017_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='обновлен'),
        ),
    ]
